name: ci

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/discord-bot:latest
          build-args: |
            DAVINCI_TOKEN=${{ secrets.DAVINCI_TOKEN }}
            SERVER_ID=${{ secrets.SERVER_ID }}
            SALAI_TOKEN=${{ secrets.SALAI_TOKEN }}
            CHANNEL_ID=${{ secrets.CHANNEL_ID }}
            MID_JOURNEY_ID=${{ secrets.MID_JOURNEY_ID }}
            USE_MESSAGED_CHANNEL=${{ secrets.USE_MESSAGED_CHANNEL }}           
